WebApp/Controllers/AccountController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System.Threading.Tasks;
using WebApp.Context;

namespace WebApp.Controllers
{
    [ApiExplorerSettings(IgnoreApi = true)]
    [Route("[controller]/[action]")]
    public class AccountController : Controller
    {
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly ILogger _logger;

        public AccountController(SignInManager<ApplicationUser> signInManager, ILogger<AccountController> logger)
        {
            _signInManager = signInManager;
            _logger = logger;
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Logout()
        {
            await _signInManager.SignOutAsync();
            _logger.LogInformation("User logged out.");
            return RedirectToPage("/Index");
        }
    }
}

WebApp/Pages/Account/AccessDenied.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Company.WebApplication1.Pages.Account
{
    public class AccessDeniedModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

WebApp/Pages/Account/ConfirmEmail.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Company.WebApplication1.Data;
using WebApp.Context;

namespace Company.WebApplication1.Pages.Account
{
    public class ConfirmEmailModel : PageModel
    {
        private readonly UserManager<ApplicationUser> _userManager;

        public ConfirmEmailModel(UserManager<ApplicationUser> userManager)
        {
            _userManager = userManager;
        }

        public async Task<IActionResult> OnGetAsync(string userId, string code)
        {
            if (userId == null || code == null)
            {
                return RedirectToPage("/Index");
            }

            var user = await _userManager.FindByIdAsync(userId);
            if (user == null)
            {
                throw new ApplicationException($"Unable to load user with ID '{userId}'.");
            }

            var result = await _userManager.ConfirmEmailAsync(user, code);
            if (!result.Succeeded)
            {
                throw new ApplicationException($"Error confirming email for user with ID '{userId}':");
            }

            return Page();
        }
    }
}

WebApp/Pages/Account/ForgotPassword.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Company.WebApplication1.Data;
using Company.WebApplication1.Services;
using Company.WebApplication1.Services.Mail;
using WebApp.Context;
namespace Company.WebApplication1.Pages.Account
{
    public class ForgotPasswordModel : PageModel
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IMailManager _emailSender;

        public ForgotPasswordModel(UserManager<ApplicationUser> userManager, IMailManager emailSender)
        {
            _userManager = userManager;
            _emailSender = emailSender;
        }

        [BindProperty]
        public InputModel Input { get; set; }

        public class InputModel
        {
            [Required]
            [EmailAddress]
            public string Email { get; set; }
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (ModelState.IsValid)
            {
                var user = await _userManager.FindByEmailAsync(Input.Email);
                if (user == null || !(await _userManager.IsEmailConfirmedAsync(user)))
                {
                    // Don't reveal that the user does not exist or is not confirmed
                    return RedirectToPage("./ForgotPasswordConfirmation");
                }

                // For more information on how to enable account confirmation and password reset please 
                // visit https://go.microsoft.com/fwlink/?LinkID=532713
                var code = await _userManager.GeneratePasswordResetTokenAsync(user);
                var callbackUrl = Url.ResetPasswordCallbackLink(user.Id, code, Request.Scheme);
                await _emailSender.SendResetPasswordAsync(Input.Email, callbackUrl);
                return RedirectToPage("./ForgotPasswordConfirmation");
            }

            return Page();
        }
    }
}

WebApp/Pages/Account/ForgotPasswordConfirmation.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Company.WebApplication1.Pages.Account
{
    public class ForgotPasswordConfirmationModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

WebApp/Pages/Account/Lockout.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Company.WebApplication1.Pages.Account
{
    public class LockoutModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

WebApp/Pages/Account/ResetPasswordConfirmation.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Company.WebApplication1.Pages.Account
{
    public class ResetPasswordConfirmationModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

WebApp/Pages/Account/SignedOut.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Company.WebApplication1.Pages.Account
{
    public class SignedOutModel : PageModel
    {
        public IActionResult OnGet()
        {
            if (User.Identity.IsAuthenticated)
            {
                // Redirect to home page if the user is authenticated.
                return RedirectToPage("/Index");
            }

            return Page();
        }
    }
}

WebApp/Pages/Examples/Profile.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Company.WebApplication1.Pages.Examples
{
    public class ProfileModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

WebApp/Pages/Settings/Account.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Company.WebApplication1.Data;
using Company.WebApplication1.Services.Mail;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Company.WebApplication1.Pages.Settings
{
    public class AccountModel : PageModel
    {
        public AccountModel() 
        {
        }

        public IActionResult OnGet()
        {
            return Page();
        }
    }
}

WebApp/Pages/Settings/Profile.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Company.WebApplication1.Data;
using Company.WebApplication1.Services.Mail;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WebApp.Context;
namespace Company.WebApplication1.Pages.Settings
{
    public class ProfileModel : PageModel
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly IMailManager _emailSender;

        public ProfileModel(UserManager<ApplicationUser> userManager, SignInManager<ApplicationUser> signInManager, IMailManager emailSender) 
            //: base(userManager, signInManager, emailSender)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _emailSender = emailSender;
        }

        [BindProperty]
        [Required]
        public string UserName { get; set; }

        [BindProperty]
        [Required][EmailAddress]
        public string Email { get; set; }

        [BindProperty]
        [Phone][Display(Name = "Phone number")]
        public string PhoneNumber { get; set; }

        public bool IsEmailConfirmed { get; set; }

        public async Task<IActionResult> OnGetAsync()
        {
            ApplicationUser user = await _userManager.GetUserAsync(User);
            if (user == null)
                throw new ApplicationException($"Unable to load user with ID '{_userManager.GetUserId(User)}'.");

            UserName = user.UserName;
            Email = user.Email;
            PhoneNumber = user.PhoneNumber;

            IsEmailConfirmed = await _userManager.IsEmailConfirmedAsync(user);

            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            ApplicationUser user = await _userManager.GetUserAsync(User);
            if (user == null) throw new ApplicationException($"Unable to load user with ID '{_userManager.GetUserId(User)}'.");

            if (UserName != user.UserName)
            {
                var setUserNameResult = await _userManager.SetUserNameAsync(user, UserName);
                if (!setUserNameResult.Succeeded)
                {
                    TempData["StatusMessage"] = $"Error on changing username." + string.Join(". ", setUserNameResult.Errors.Select(p => p.Description));
                    return RedirectToPage();
                    //throw new ApplicationException($"Unexpected error occurred setting email for user with ID '{user.Id}'.");
                }
            }

            if (Email != user.Email)
            {
                var setEmailResult = await _userManager.SetEmailAsync(user, Email);
                if (!setEmailResult.Succeeded)
                {
                    TempData["StatusMessage"] = $"Error on changing email. '{Email}' use in other account and must be unique.";
                    return RedirectToPage();
                    //throw new ApplicationException($"Unexpected error occurred setting email for user with ID '{user.Id}'.");
                }
            }

            if (PhoneNumber != user.PhoneNumber)
            {
                var setPhoneResult = await _userManager.SetPhoneNumberAsync(user, PhoneNumber);
                if (!setPhoneResult.Succeeded)
                {
                    throw new ApplicationException($"Unexpected error occurred setting phone number for user with ID '{user.Id}'.");
                }
            }

            TempData["StatusMessage"] = "Your profile has been updated";

            return RedirectToPage();
        }

        public async Task<IActionResult> OnPostSendVerificationEmailAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            ApplicationUser user = await _userManager.GetUserAsync(User);
            if (user == null) throw new ApplicationException($"Unable to load user with ID '{_userManager.GetUserId(User)}'.");

            var code = await _userManager.GenerateEmailConfirmationTokenAsync(user);
            var callbackUrl = Url.EmailConfirmationLink(user.Id, code, Request.Scheme);
            await _emailSender.SendEmailConfirmationAsync(user.Email, callbackUrl);

            TempData["StatusMessage"] = "Verification email sent. Please check your email.";

            return RedirectToPage();
        }
    }
}

WebApp/Pages/Settings/Security.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using Company.WebApplication1.Data;
using Company.WebApplication1.Services.Mail;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using WebApp.Context;
namespace Company.WebApplication1.Pages.Settings
{
    public class SecurityModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        private readonly UserManager<ApplicationUser> _userManager;
        private readonly SignInManager<ApplicationUser> _signInManager;

        public SecurityModel(UserManager<ApplicationUser> userManager, SignInManager<ApplicationUser> signInManager, ILogger<IndexModel> logger) 
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _logger = logger;
        }

        public IList<UserLoginInfo> CurrentLogins { get; set; }

        public IList<AuthenticationScheme> OtherLogins { get; set; }

        public bool ShowRemoveButton { get; set; }

        public bool Is2faEnabled { get; set; }
        public int RecoveryCodesLeft { get; set; }
        public bool HasAuthenticator { get; set; }

        public async Task<IActionResult> OnGetAsync()
        {
            var user = await _userManager.GetUserAsync(User);
            if (user == null)
                throw new ApplicationException($"Unable to load user with ID '{_userManager.GetUserId(User)}'.");

            CurrentLogins = await _userManager.GetLoginsAsync(user);
            OtherLogins = (await _signInManager.GetExternalAuthenticationSchemesAsync())
                .Where(auth => CurrentLogins.All(ul => auth.Name != ul.LoginProvider))
                .ToList();

            ShowRemoveButton = user.PasswordHash != null || CurrentLogins.Count > 1;

            Is2faEnabled = await _userManager.GetTwoFactorEnabledAsync(user);
            RecoveryCodesLeft = await _userManager.CountRecoveryCodesAsync(user);
            HasAuthenticator = await _userManager.GetAuthenticatorKeyAsync(user) != null;

            return Page();
        }

        public IActionResult OnPost()
        {
            return NotFound();
        }

        public async Task<IActionResult> OnPostRemoveLoginAsync(string loginProvider, string providerKey)
        {
            var user = await _userManager.GetUserAsync(User);
            if (user == null)
            {
                throw new ApplicationException($"Unable to load user with ID '{_userManager.GetUserId(User)}'.");
            }

            var result = await _userManager.RemoveLoginAsync(user, loginProvider, providerKey);
            if (!result.Succeeded)
            {
                throw new ApplicationException($"Unexpected error occurred removing external login for user with ID '{user.Id}'.");
            }

            await _signInManager.SignInAsync(user, isPersistent: false);

            TempData["StatusMessage"] = $"The external login for {loginProvider} was removed.";

            return RedirectToPage();
        }

        public async Task<IActionResult> OnPostLinkLoginAsync(string provider)
        {
            // Clear the existing external cookie to ensure a clean login process
            await HttpContext.SignOutAsync(IdentityConstants.ExternalScheme);

            // Request a redirect to the external login provider to link a login for the current user
            var redirectUrl = Url.Page("./Security", pageHandler: "LinkLoginCallback");
            var properties = _signInManager.ConfigureExternalAuthenticationProperties(provider, redirectUrl, _userManager.GetUserId(User));

            return new ChallengeResult(provider, properties);
        }

        public async Task<IActionResult> OnGetLinkLoginCallbackAsync()
        {
            var user = await _userManager.GetUserAsync(User);
            if (user == null)
                throw new ApplicationException($"Unable to load user with ID '{_userManager.GetUserId(User)}'.");

            var info = await _signInManager.GetExternalLoginInfoAsync(await _userManager.GetUserIdAsync(user));
            if (info == null)
            {
                throw new ApplicationException($"Unexpected error occurred loading external login info for user with ID '{user.Id}'.");
            }

            var result = await _userManager.AddLoginAsync(user, info);
            if (!result.Succeeded)
            {
                throw new ApplicationException($"Unexpected error occurred adding external login for user with ID '{user.Id}'.");
            }

            // Clear the existing external cookie to ensure a clean login process
            await HttpContext.SignOutAsync(IdentityConstants.ExternalScheme);
            
            TempData["StatusMessage"] = $"The external login for {info.ProviderDisplayName} was added.";
            return RedirectToPage();
        }

        public async Task<IActionResult> OnPostDisable2FAAsync()
        {
            var user = await _userManager.GetUserAsync(User);
            if (user == null)
                throw new ApplicationException($"Unable to load user with ID '{_userManager.GetUserId(User)}'.");

            var disable2faResult = await _userManager.SetTwoFactorEnabledAsync(user, false);
            if (!disable2faResult.Succeeded)
            {
                throw new ApplicationException($"Unexpected error occurred disabling 2FA for user with ID '{_userManager.GetUserId(User)}'.");
            }

            _logger.LogInformation("User with ID '{UserId}' has disabled 2fa.", _userManager.GetUserId(User));

            return RedirectToPage();
        }
    }
}

WebApp/Pages/Settings/Profile.cshtml
@page
@model ProfileModel
@{
    ViewData["Title"] = "Profile";
}

@inject Company.WebApplication1.Services.Profile.ProfileManager ProfileManager

<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        My Profile
    </h1>
    <ol class="breadcrumb">
        <li><a href="/"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="#">Settings</a></li>
        <li class="active">My Profile</li>
    </ol>
</section>


<!-- Main content -->
<section class="content">

    <div class="row">
        <div class="col-lg-2">

        </div>
        <!-- /.col -->

        <div class="col-lg-8">

            <!-- Profile Settings -->
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Public profile</h3>
                </div>
                <div class="box-body box-profile">
                    <form class="form-horizontal" method="post">
                        <div class="form-group">
                            <label for="inputUserName" class="col-sm-2 control-label">Username</label>

                            <div class="col-sm-10">
                                <input asp-for="UserName" class="form-control" id="inputUserName" placeholder="Username">
                                <span asp-validation-for="UserName" class="help-block"></span>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputEmail" class="col-sm-2 control-label">Email</label>
                            <div class="col-sm-10">
                                @if (ProfileManager.IsEmailConfirmed(ProfileManager.CurrentUser))
                                {
                                    <div class="input-group">
                                        <input asp-for="Email" type="email" class="form-control" id="inputEmail" placeholder="Email">
                                        <span class="input-group-addon" aria-hidden="true"><span class="glyphicon glyphicon-ok text-success"></span></span>
                                    </div>
                                }
                                else
                                {
                                    <input asp-for="Email" type="email" class="form-control" id="inputEmail" placeholder="Email">
                                    <button asp-page-handler="SendVerificationEmail" class="btn btn-link">Send verification email</button>
                                }
                                <span asp-validation-for="Email" class="help-block"></span>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputPhone" class="col-sm-2 control-label">Phone</label>

                            <div class="col-sm-10">
                                <input asp-for="PhoneNumber" class="form-control" id="inputPhoneNumber" placeholder="Phone" data-inputmask='"mask": "+7 (999) 999-9999"' data-mask>
                                <span asp-validation-for="PhoneNumber" class="help-block"></span>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-primary">Save</button>
                            </div>
                        </div>
                    </form>
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        </div>
        <!-- /.col -->

        <div class="col-lg-2">

        </div>
        <!-- /.col -->
    </div>
    <!-- /.row -->

</section>
<!-- /.content -->

@section Scripts {
    <!-- InputMask -->
    <script src="~/libs/inputmask/jquery.inputmask.bundle.min.js"></script>

    <!-- Page script -->
    <script>
        $(function () {
            //InputMask
            $('[data-mask]').inputmask();
        });
    </script>
}

WebApp/Pages/Settings/Security.cshtml
@page
@model Company.WebApplication1.Pages.Settings.SecurityModel
@{
    ViewData["Title"] = "Security";
}

<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        My Profile
    </h1>
    <ol class="breadcrumb">
        <li><a href="/"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="#">Settings</a></li>
        <li class="active">My Profile</li>
    </ol>
</section>


<!-- Main content -->
<section class="content">

    <div class="row">
        <div class="col-lg-2">

        </div>
        <!-- /.col -->

        <div class="col-lg-8">

            <h4>External Logins</h4>

            <ul class="list-group">
                @foreach (var login in Model.CurrentLogins)
                {
                    <li class="list-group-item">
                        <div class="row">
                            <div class="col-xs-4 text-left nowrap">
                                <span class="btn btn-social-icon btn-@login.LoginProvider.ToLower()">
                                    <i class="fa fa-@login.LoginProvider.ToLower()"></i>
                                </span>
                                <strong>@login.ProviderDisplayName</strong> <span class="label label-primary">Connected</span>
                            </div>
                            <div class="col-xs-8 text-right">
                                @if (Model.ShowRemoveButton)
                                {
                                    <form asp-page-handler="RemoveLogin" method="post">
                                        <div>
                                            <input asp-for="@login.LoginProvider" name="LoginProvider" type="hidden" />
                                            <input asp-for="@login.ProviderKey" name="ProviderKey" type="hidden" />
                                            <button type="submit" class="btn btn-danger" title="Remove this @login.LoginProvider login from your account">
                                                <i class="fa fa-remove"></i> Disconnect
                                            </button>
                                        </div>
                                    </form>
                                }
                            </div>
                        </div>
                    </li>
                }
                @foreach (var provider in Model.OtherLogins)
                {
                    <li class="list-group-item">
                        <div class="row">
                            <div class="col-xs-4 text-left nowrap">
                                <span class="btn btn-social-icon btn-@provider.DisplayName.ToLower()">
                                    <i class="fa fa-@provider.DisplayName.ToLower()"></i>
                                </span>
                                <strong>@provider.DisplayName</strong>
                            </div>
                            <div class="col-xs-8 text-right">
                                <form asp-page-handler="LinkLogin" method="post" class="form-horizontal">
                                    <button type="submit" class="btn btn-primary" name="provider" value="@provider.Name">
                                        <i class="fa fa-plus"></i> Connect
                                    </button>
                                </form>
                            </div>
                        </div>
                    </li>
                }
            </ul>

            <h4>Two-factor authentication</h4>
            @if (Model.Is2faEnabled)
            {
                @if (Model.RecoveryCodesLeft == 0)
                {
                    <div class="alert alert-danger">
                        <strong>You have no recovery codes left.</strong>
                        <p>You must <a asp-page="./TwoFactorAuth/RecoveryCodes">generate a new set of recovery codes</a> before you can log in with a recovery code.</p>
                    </div>
                }
                else if (Model.RecoveryCodesLeft == 1)
                {
                    <div class="alert alert-danger">
                        <strong>You have 1 recovery code left.</strong>
                        <p>You can <a asp-page="./TwoFactorAuth/RecoveryCodes">generate a new set of recovery codes</a>.</p>
                    </div>
                }
                else if (Model.RecoveryCodesLeft <= 3)
                {
                    <div class="alert alert-warning">
                        <strong>You have @Model.RecoveryCodesLeft recovery codes left.</strong>
                        <p>You should <a asp-page="./TwoFactorAuth/RecoveryCodes">generate a new set of recovery codes</a>.</p>
                    </div>
                }
            }

            <ul class="list-group">

                <li class="list-group-item">
                    <div class="row">
                        @if (Model.Is2faEnabled)
                        {
                            <div class="col-xs-4 text-left nowrap">
                                Status: <span class="text-green"><strong>Enabled</strong> <i class="fa fa-check"></i></span>
                            </div>
                            <div class="col-xs-8 text-right">
                                <form asp-page-handler="Disable2FA" method="post" class="form-group">
                                    <a href="./TwoFactorAuth" class="btn btn-primary">
                                        <i class="fa fa-edit"></i> Edit
                                    </a>

                                    <button class="btn btn-danger" type="submit" title="Disable two-factor authentication"><i class="fa fa-remove"></i></button>
                                </form>
                            </div>
                        }
                        else
                        {
                            <div class="col-xs-4 text-left nowrap">
                                Status: <span class="text-red"><strong>Off</strong> <i class="fa fa-remove"></i></span>
                            </div>
                            <div class="col-xs-8 text-right">
                                <a href="./TwoFactorAuth" class="btn btn-primary">
                                    <i class="fa fa-lock"></i> Set up two-factor authentication
                                </a>
                            </div>
                        }
                    </div>
                </li>
                @if (Model.Is2faEnabled)
                {
                    <li class="list-group-item">
                        Save your <a href="./TwoFactorAuth/RecoveryCodes">recovery codes</a> in a safe place. They will allow you to access your account if you ever lose your phone.
                    </li>
                }
            </ul>

        </div>
        <!-- /.col -->

        <div class="col-lg-2">

        </div>
        <!-- /.col -->
    </div>
    <!-- /.row -->

</section>
<!-- /.content -->